# apiVersion: v1
# kind: ConfigMap
# metadata:
#  name: frontend
#  namespace: expense # mysql component service name
# data:
#   DB_HOST: mysql

 
# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  # these lables belongs to replicaset resources
  labels:
    component: frontend
    project: expense
    tier: app
    # how many replicas required
spec:
  replicas: 3
  # which pod you want replica
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: app
# pod definition
  template:
    metadata:
    # selector labels must match below labels
      labels:
        component: frontend
        project: expense
        tier: app
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:v1.0
        # envFrom:
        # - configMapRef:
        #    name: frontend

---

kind: Service
apiVersion: v1
metadata:
 name: frontend
 namespace: expense
spec:
type: LoadBalancer
 selector:
  component: frontend
  project: expense
  tier: app
 ports:
  - protocol: TCP
    port: 80
    targetPort: 80

