apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # these lables belongs to replicaset resources
  labels:
    component: mysql
    project: expense
    tier: db
    # how many replicas required
spec:
  replicas: 3
  # which pod you want replica
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
# pod definition
  template:
    metadata:
    # selector labels must match below labels
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0

---

kind: Service
apiVersion: v1
metadata:
 name: mysql
 namespace: expense
spec:
 selector:
  component: mysql
  project: expense
  tier: db
 ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306 

